= NextCloud on Docker with LetsEncrypt SSL, PostgreSQL backend, Collabora online office, Cron support

In my perception the official examples did not provide a working _home production ready_ Docker example to host a private NextCloud on your own server.



## Features

* PostgreSQL backend and nginx Frontend: Based on link:https://github.com/nextcloud/docker/blob/master/.examples/docker-compose/with-nginx-proxy/postgres/apache/docker-compose.yml[NextCloud PostgreSQL Apache example]
* link:https://github.com/nextcloud/docker/blob/master/.examples/dockerfiles/cron/apache/supervisord.conf[Cron-based background Tasks using supervisord]
* Letsencrypt SSL https-support
* Working https://github.com/nextcloud/docker/pull/630[Collabora Online Office (CODE) integration]



## How to get it running

To get this running, have an installed `docker-compose` available and:

1. register two dynamic domains i.e. at https://freedns.org
- one for your nextcloud: `mynextcloud.mooo.com`
- one only to host Collabora: `myoffice.mooo.com`
2. publicly expose TCP port 80 & 443 of your host in router
3. Adjust all `pass:[[##VALUES##]]` in the files: `docker-compose.yml` and `db.env`
4. Run `sudo docker-compose up --build`. I added/adjusted my `/etc/docker/daemon.js` to define a custom data storage location: `{ "data-root": "/srv/dockerdata" }`
5. Activate Collabora plugin in NextCloud und define pass:[https://[##myoffice.mooo.com##]] as URL. Ignore the _Saved with error: Collabora Online should use the same protocol as the server installation_ message.



## How to upgrade & rebuild your installation
Simply do the following. Due to the persistent Docker volumes this will retain all your data and even your running login sessions.

```
   $ sudo docker-compose down
   $ sudo docker-compose build --pull
   $ sudo docker-compose up -d
```

I'm not sure, but after major release upgrade a subsequent `sudo docker-compose exec --user www-data app php occ db:add-missing-indices` might be necessary or not. At least it won't hurt.

## Versions
2019-11-01::  Initial running version
2019-12-09::  Got Collabora CODE Integration working
